sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gmdom/website .

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-101964887726"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key